server:
  port: 8888
spring:
  application:
    name: spring-gray-gateway
  cloud:
    nacos:
      discovery:
        namespace: 89bdd4e0-a92c-412d-9a67-a4e4a9531d05
        password: nacos
        server-addr: 192.168.0.110:8848
        username: nacos
    gateway:
      routes:
        # 路由的ID，没有固定规则，但要求唯一，建议配合服务名
        - id: spring-gray-article
          # 匹配后提供服务的路由地址
          uri: lb://spring-gray-article
          # 断言，路径相匹配的进行路由
          predicates:
            - Path=/article/**
        # 路由的ID，没有固定规则，但要求唯一，建议配合服务名
        - id: spring-gray-comment
          # 匹配后提供服务的路由地址
          uri: lb://spring-gray-comment
          # 断言，路径相匹配的进行路由
          predicates:
            - Path=/comment/**
#spring-gray-article:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.example.springgraygateway.config.GrayRuleConfig
